services:
  - type: web
    name: api
    runtime: docker
    plan: free
    autoDeploy: true
    dockerfilePath: servers/api/Dockerfile
    buildFilter:
      paths:
        - servers/api/**
        - packages/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hashfund
          property: connectionString
      - key: HTTP_RPC_ENDPOINT
        sync: false
      - key: WSS_RPC_ENDPOINT
        sync: false
      - key: SECRET_KEY
        generateValue: true
      - key: IMAGEKIT_PUBLIC_KEY
        sync: false
      - key: IMAGEKIT_PRIVATE_KEY
        sync: false
      - key: IMAGEKIT_URL_ENDPOINT
        sync: false
    domains:
      - "v1.api.hashfund.fun"
  - type: web
    runtime: docker
    name: watchdog
    plan: free
    autoDeploy: true
    dockerfilePath: servers/watchdog/Dockerfile
    buildFilter:
      paths:
        - servers/watchdog/**
        - servers/api/**
        - packages/**
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: hashfund
          property: connectionString
      - key: ANCHOR_PROVIDER_URL
        sync: false
      - key: WALLET_PRIVATE_KEY
        sync: false
databases:
  - name: hashfund
    databaseName: hashfund
    user: admin
    plan: free

