services:
  - type: web
    name: api
    runtime: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: servers/api/Dockerfile
    buildFilter:
      ignoredPaths:
        - www/web/*.{json,ts}
        - www/web/**/*.{json,ts}
        - servers/api/*.{json,ts}
        - servers/api/**/*.{json,ts}
        - packages/program/*.{json,ts}
        - packages/program/**/*.{json,ts}         
    envVars:
      - fromGroup: api
      - key: DATABASE_URL
        fromDatabase:
          name: hashfund
          property: connectionString
    domains:
      - "v1.api.hashfund.fun"
  - type: worker
    runtime: docker
    name: watchdog
    plan: starter
    autoDeploy: true
    dockerfilePath: servers/watchdog/Dockerfile
    buildFilter:
      paths:
        - servers/api/*.{json,ts}
        - servers/api/**/*.{json,ts}
        - servers/watchdog/*.{json,ts}
        - servers/watchdog/**/*.{json,ts}   
        - packages/program/*.{json,ts}
        - packages/program/**/*.{json,ts}  
    envVars:
      - fromGroup: api
      - key: DATABASE_URL
        fromDatabase:
          name: hashfund
          property: connectionString
  - type: web
    runtime: docker
    name: web
    plan: starter
    autoDeploy: true
    dockerfilePath: www/web/Dockerfile
    buildFilter:
      paths:
        - packages/program/*.{json,ts}
        - packages/program/**/*.{json,ts} 
    envVars:
      - fromGroup: api
      - key: NEXT_PUBLIC_BASE_API_URL
        fromService:
          type: web
          name: api
          envVarKey: RENDER_EXTERNAL_URL
databases:
  - name: hashfund
    databaseName: hashfund
    user: admin
    plan: starter

