services:
  - type: web
    name: api
    runtime: docker
    plan: starter
    autoDeploy: true
    dockerfilePath: servers/api/Dockerfile
    buildFilter:
      paths:
        - servers/api/*.ts
        - servers/api/**/*.json
        - servers/api/Dockerfile
        - packages/program/*.json
        - packages/program/**/*.ts
    envVars:
      - fromGroup: api
      - key: DATABASE_URL
        fromDatabase:
          name: hashfund
          property: connectionString
    domains:
      - "v1.api.hashfund.fun"
  - type: worker
    runtime: docker
    name: watchdog
    plan: starter
    autoDeploy: true
    dockerfilePath: servers/watchdog/Dockerfile
    buildFilter:
      paths:
        - servers/api/*.ts
        - servers/api/**/*.json
        - servers/api/Dockerfile
        - servers/watchdog/*.json
        - servers/watchdog/**/*.ts
        - packages/program/*.json
        - packages/program/**/*.ts
    envVars:
      - fromGroup: api
      - key: DATABASE_URL
        fromDatabase:
          name: hashfund
          property: connectionString
  - type: web
    runtime: docker
    name: web
    plan: starter
    autoDeploy: true
    dockerfilePath: www/web/Dockerfile
    buildFilter:
      paths:
        - www/web/*.json
        - www/web/**/*.ts
        - www/web/Dockerfile
        - packages/program/*.json
        - packages/program/**/*.ts
    envVars:
      - fromGroup: web
      - key: NEXT_PUBLIC_BASE_API_URL
        fromService:
          type: web
          name: api
          envVarKey: RENDER_EXTERNAL_URL
databases:
  - name: hashfund
    databaseName: hashfund
    user: admin
    plan: starter

